version: '2.2'
services:
  mongo:
      image: mongo:4.4
      container_name: mongodb
      volumes:
          - ./data/db:/data/db
      ports:
        - 27017:27017
      environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root